import pathlib,sys
p=pathlib.Path(sys.argv[1]);s=p.read_text(encoding='utf-8')

def once(a,b,n):
 global s
 c=s.count(a)
 if c!=1: raise RuntimeError(f'{n}: {c}')
 s=s.replace(a,b,1)

def span(sig):
 a=s.index(sig);q=s.index('{',a);d=0
 for i in range(q,len(s)):
  if s[i]=='{':d+=1
  elif s[i]=='}':
   d-=1
   if d==0:return a,i+1
 raise RuntimeError(sig)

def fn(sig,new):
 global s
 a,b=span(sig);s=s[:a]+new+s[b:]

once('Premium Plus Combo | v4.8.20','Premium Plus Combo | v4.8.21','version')
once('constexpr int IDC_WARRIOR_CAL = 1807;','''constexpr int IDC_WARRIOR_CAL = 1807;\nconstexpr int IDC_WARRIOR_DESCENT_BAR=1808,IDC_WARRIOR_DESCENT_SLOT=1809,IDC_WARRIOR_DESCENT_KEY=1810;\nconstexpr int IDC_WARRIOR_ECHO_ENABLE=1811,IDC_WARRIOR_ECHO_BAR=1812,IDC_WARRIOR_ECHO_SLOT=1813,IDC_WARRIOR_ECHO_INTERVAL=1814,IDC_WARRIOR_ECHO_UNIT=1815;''','ids')
once('  NormalizedRect inventoryRect; // optional visual hint, never the sole detector\n};','''  NormalizedRect inventoryRect; // optional visual hint, never the sole detector\n  int descentBar=1,descentSlot=1,descentHotkey=VK_F7;\n  bool echoEnabled=false;int echoBar=1,echoSlot=1,echoIntervalValue=30,echoIntervalUnit=0; // 0 sec / 1 min\n};''','settings')
once('HWND warriorEnable{},warriorShieldSlot{},warriorShieldKey{},warriorWeaponSlot{},warriorWeaponKey{},warriorCal{},warriorSave{},warriorStatus{};','HWND warriorEnable{},warriorShieldSlot{},warriorShieldKey{},warriorWeaponSlot{},warriorWeaponKey{},warriorCal{},warriorSave{},warriorStatus{},warriorDescentBar{},warriorDescentSlot{},warriorDescentKey{},warriorEchoEnable{},warriorEchoBar{},warriorEchoSlot{},warriorEchoInterval{},warriorEchoUnit{};','ui')
once('std::atomic<bool> g_warriorBusy{false};','''std::atomic<bool> g_warriorBusy{false};\nstd::atomic<unsigned> g_warriorEquipPending{0},g_warriorDescentPending{0},g_echoScheduleRevision{1};\nstd::atomic<ULONGLONG> g_echoLastFireAt{0};std::atomic<unsigned long> g_echoFireCount{0};''','runtime')

once('''    g_warrior.inventoryRect={(int)ReadDword(k,L"InvX",0),(int)ReadDword(k,L"InvY",0),(int)ReadDword(k,L"InvW",0),(int)ReadDword(k,L"InvH",0)};\n    RegCloseKey(k);''','''    g_warrior.inventoryRect={(int)ReadDword(k,L"InvX",0),(int)ReadDword(k,L"InvY",0),(int)ReadDword(k,L"InvW",0),(int)ReadDword(k,L"InvH",0)};\n    g_warrior.descentBar=ClampD(ReadDword(k,L"DescentBar",1),1,12);g_warrior.descentSlot=ClampD(ReadDword(k,L"DescentSlot",1),1,10);g_warrior.descentHotkey=ClampD(ReadDword(k,L"DescentHotkey",VK_F7),1,255);\n    g_warrior.echoEnabled=ReadDword(k,L"EchoEnabled",0)!=0;g_warrior.echoBar=ClampD(ReadDword(k,L"EchoBar",1),1,12);g_warrior.echoSlot=ClampD(ReadDword(k,L"EchoSlot",1),1,10);g_warrior.echoIntervalValue=ClampD(ReadDword(k,L"EchoIntervalValue",30),1,3600);g_warrior.echoIntervalUnit=ClampD(ReadDword(k,L"EchoIntervalUnit",0),0,1);\n    if(g_warrior.descentHotkey==g_warrior.shieldHotkey)g_warrior.descentHotkey=VK_F7==g_warrior.shieldHotkey?VK_F11:VK_F7;\n    RegCloseKey(k);''','load')
fn('void SaveWarrior()',r'''void SaveWarrior(){HKEY k{};std::lock_guard<std::mutex>lk(g_settingsMutex);if(RegCreateKeyExW(HKEY_CURRENT_USER,kWarriorRegistry,0,nullptr,0,KEY_READ|KEY_WRITE,nullptr,&k,nullptr)!=ERROR_SUCCESS)return;WriteDword(k,L"Enabled",g_warrior.enabled?1:0);WriteDword(k,L"ShieldSlot",g_warrior.shieldSlot);WriteDword(k,L"WeaponSlot",g_warrior.weaponSlot);WriteDword(k,L"SharedHotkey",g_warrior.shieldHotkey);WriteDword(k,L"ShieldHotkey",g_warrior.shieldHotkey);WriteDword(k,L"WeaponHotkey",g_warrior.shieldHotkey);WriteDword(k,L"InvX",g_warrior.inventoryRect.x);WriteDword(k,L"InvY",g_warrior.inventoryRect.y);WriteDword(k,L"InvW",g_warrior.inventoryRect.w);WriteDword(k,L"InvH",g_warrior.inventoryRect.h);WriteDword(k,L"DescentBar",g_warrior.descentBar);WriteDword(k,L"DescentSlot",g_warrior.descentSlot);WriteDword(k,L"DescentHotkey",g_warrior.descentHotkey);WriteDword(k,L"EchoEnabled",g_warrior.echoEnabled?1:0);WriteDword(k,L"EchoBar",g_warrior.echoBar);WriteDword(k,L"EchoSlot",g_warrior.echoSlot);WriteDword(k,L"EchoIntervalValue",g_warrior.echoIntervalValue);WriteDword(k,L"EchoIntervalUnit",g_warrior.echoIntervalUnit);RegCloseKey(k);}''')

fn('void ReadWarriorUi(bool persist=true)',r'''void ReadWarriorUi(bool persist=true){WarriorSettings n;{std::lock_guard<std::mutex>lk(g_settingsMutex);n=g_warrior;}int os=n.shieldSlot,ow=n.weaponSlot;bool oe=n.echoEnabled;int ob=n.echoBar,osl=n.echoSlot,ov=n.echoIntervalValue,ou=n.echoIntervalUnit;if(g_ui.warriorEnable)n.enabled=SendMessageW(g_ui.warriorEnable,BM_GETCHECK,0,0)==BST_CHECKED;if(g_ui.warriorShieldSlot)n.shieldSlot=GetInt(g_ui.warriorShieldSlot,n.shieldSlot,1,28);if(g_ui.warriorWeaponSlot)n.weaponSlot=GetInt(g_ui.warriorWeaponSlot,n.weaponSlot,1,28);if(g_ui.warriorDescentBar)n.descentBar=ComboVal(g_ui.warriorDescentBar,1,12,n.descentBar);if(g_ui.warriorDescentSlot)n.descentSlot=ComboVal(g_ui.warriorDescentSlot,1,10,n.descentSlot);if(g_ui.warriorEchoEnable)n.echoEnabled=SendMessageW(g_ui.warriorEchoEnable,BM_GETCHECK,0,0)==BST_CHECKED;if(g_ui.warriorEchoBar)n.echoBar=ComboVal(g_ui.warriorEchoBar,1,12,n.echoBar);if(g_ui.warriorEchoSlot)n.echoSlot=ComboVal(g_ui.warriorEchoSlot,1,10,n.echoSlot);if(g_ui.warriorEchoInterval)n.echoIntervalValue=GetInt(g_ui.warriorEchoInterval,n.echoIntervalValue,1,3600);if(g_ui.warriorEchoUnit){int q=(int)SendMessageW(g_ui.warriorEchoUnit,CB_GETCURSEL,0,0);if(q>=0&&q<=1)n.echoIntervalUnit=q;}n.weaponHotkey=n.shieldHotkey;{std::lock_guard<std::mutex>lk(g_settingsMutex);g_warrior=n;}if(os!=n.shieldSlot||ow!=n.weaponSlot)g_warriorNextEquip=0;if(oe!=n.echoEnabled||ob!=n.echoBar||osl!=n.echoSlot||ov!=n.echoIntervalValue||ou!=n.echoIntervalUnit)g_echoScheduleRevision.fetch_add(1);if(persist)SaveWarrior();}''')
fn('void PopulateWarriorUi()',r'''void PopulateWarriorUi(){if(!g_ui.warriorEnable)return;WarriorSettings w;{std::lock_guard<std::mutex>lk(g_settingsMutex);w=g_warrior;}SendMessageW(g_ui.warriorEnable,BM_SETCHECK,w.enabled?BST_CHECKED:BST_UNCHECKED,0);SetWindowTextW(g_ui.warriorShieldSlot,std::to_wstring(w.shieldSlot).c_str());SetWindowTextW(g_ui.warriorWeaponSlot,std::to_wstring(w.weaponSlot).c_str());if(g_ui.warriorDescentBar)SetCombo(g_ui.warriorDescentBar,w.descentBar,1);if(g_ui.warriorDescentSlot)SetCombo(g_ui.warriorDescentSlot,w.descentSlot,1);if(g_ui.warriorEchoEnable)SendMessageW(g_ui.warriorEchoEnable,BM_SETCHECK,w.echoEnabled?BST_CHECKED:BST_UNCHECKED,0);if(g_ui.warriorEchoBar)SetCombo(g_ui.warriorEchoBar,w.echoBar,1);if(g_ui.warriorEchoSlot)SetCombo(g_ui.warriorEchoSlot,w.echoSlot,1);if(g_ui.warriorEchoInterval)SetWindowTextW(g_ui.warriorEchoInterval,std::to_wstring(w.echoIntervalValue).c_str());if(g_ui.warriorEchoUnit)SendMessageW(g_ui.warriorEchoUnit,CB_SETCURSEL,w.echoIntervalUnit,0);}''')
once('if(g_ui.warriorShieldKey)set(g_ui.warriorShieldKey,L"Ekipman Değiştir",w.shieldHotkey);','if(g_ui.warriorShieldKey)set(g_ui.warriorShieldKey,L"Ekipman Değiştir",w.shieldHotkey);if(g_ui.warriorDescentKey)set(g_ui.warriorDescentKey,L"Descent",w.descentHotkey);','hotkey label')

old='''int t=g_assignTarget.load();if(t&&!injected){bool allowed=vk!=VK_LBUTTON&&vk!=VK_RBUTTON;if(t<=5)allowed=allowed&&!ConflictWithRogue(vk,t);else{RogueSettings cr;AttackSettings ca;MobSettings cm;{std::lock_guard<std::mutex>lk(g_settingsMutex);cr=g_rogue;ca=g_attack;cm=g_mob;}allowed=allowed&&vk!='R'&&vk!=cr.startHotkey&&vk!=cr.stopHotkey&&vk!=cr.cureHotkey&&vk!=ca.startHotkey&&vk!=ca.stopHotkey&&vk!=cm.startHotkey&&vk!=cm.stopHotkey;}if(allowed){std::lock_guard<std::mutex>lk(g_settingsMutex);if(t==1)g_rogue.startHotkey=vk;else if(t==2)g_rogue.stopHotkey=vk;else if(t==3)g_rogue.cureHotkey=vk;else if(t==4)g_attack.startHotkey=vk;else if(t==5)g_attack.stopHotkey=vk;else if(t==6)g_mob.startHotkey=vk;else if(t==7)g_mob.stopHotkey=vk;else if(t==8){g_warrior.shieldHotkey=vk;g_warrior.weaponHotkey=vk;}g_assignTarget=0;PostMessageW(g_ui.main,WM_APP_ASSIGN_DONE,t,vk);}return 1;}'''
new='''int t=g_assignTarget.load();if(t&&!injected){bool allowed=vk!=VK_LBUTTON&&vk!=VK_RBUTTON;if(t<=5)allowed=allowed&&!ConflictWithRogue(vk,t);else{RogueSettings cr;AttackSettings ca;MobSettings cm;WarriorSettings cw;{std::lock_guard<std::mutex>lk(g_settingsMutex);cr=g_rogue;ca=g_attack;cm=g_mob;cw=g_warrior;}allowed=allowed&&vk!='R'&&vk!=cr.startHotkey&&vk!=cr.stopHotkey&&vk!=cr.cureHotkey&&vk!=ca.startHotkey&&vk!=ca.stopHotkey&&vk!=cm.startHotkey&&vk!=cm.stopHotkey;if(t==8)allowed=allowed&&vk!=cw.descentHotkey;if(t==9)allowed=allowed&&vk!=cw.shieldHotkey;}if(allowed){std::lock_guard<std::mutex>lk(g_settingsMutex);if(t==1)g_rogue.startHotkey=vk;else if(t==2)g_rogue.stopHotkey=vk;else if(t==3)g_rogue.cureHotkey=vk;else if(t==4)g_attack.startHotkey=vk;else if(t==5)g_attack.stopHotkey=vk;else if(t==6)g_mob.startHotkey=vk;else if(t==7)g_mob.stopHotkey=vk;else if(t==8){g_warrior.shieldHotkey=vk;g_warrior.weaponHotkey=vk;}else if(t==9)g_warrior.descentHotkey=vk;g_assignTarget=0;PostMessageW(g_ui.main,WM_APP_ASSIGN_DONE,t,vk);}return 1;}'''
once(old,new,'assign')
once('if(ww.enabled&&vk==ww.shieldHotkey){HWND fg=GetForegroundWindow();if(fg&&!IsOurUiWindow(fg)){RememberGameWindow();if(!g_warriorBusy.load()){g_warriorRequestWindow=(ULONG_PTR)fg;g_warriorRequest=1;if(g_warriorEvent)SetEvent(g_warriorEvent);}return 1;}}','''if(ww.enabled&&vk==ww.shieldHotkey){HWND fg=GetForegroundWindow();if(fg&&!IsOurUiWindow(fg)){RememberGameWindow();g_warriorRequestWindow=(ULONG_PTR)fg;g_warriorEquipPending.fetch_add(1);if(g_warriorEvent)SetEvent(g_warriorEvent);return 1;}}\n  if(ww.enabled&&vk==ww.descentHotkey){HWND fg=GetForegroundWindow();if(fg&&!IsOurUiWindow(fg)){RememberGameWindow();g_warriorRequestWindow=(ULONG_PTR)fg;g_warriorDescentPending.fetch_add(1);if(g_warriorEvent)SetEvent(g_warriorEvent);return 1;}}''','hotkeys')

once('int WarriorToggleSlot(const WarriorSettings&w,int phase){return (phase&1)?w.weaponSlot:w.shieldSlot;}','''int WarriorToggleSlot(const WarriorSettings&w,int phase){return (phase&1)?w.weaponSlot:w.shieldSlot;}\nULONGLONG WarriorEchoIntervalMs(const WarriorSettings&w){ULONGLONG v=(ULONGLONG)std::clamp(w.echoIntervalValue,1,3600);return v*(w.echoIntervalUnit?60000ULL:1000ULL);}\nbool WarriorTakePending(std::atomic<unsigned>&p){unsigned v=p.load();while(v){if(p.compare_exchange_weak(v,v-1))return true;}return false;}\nbool WarriorCastBarSlot(HWND game,int bar,int slot){if(!game||GetForegroundWindow()!=game)return false;FifoTicketGuard gate(g_gameInputGate);if(!g_running||GetForegroundWindow()!=game||g_chatMode.load()||g_cureExclusive.load()||g_potionExclusive.load())return false;bool ok=DirectTimedTapUnlocked(BarToVk(std::clamp(bar,1,12)),9000,900);if(!ok)return false;PreciseDelayUs(15000);return DirectTimedTapUnlocked(SlotToVk(std::clamp(slot,1,10)),9000,900);}''','helpers')
fn('void WarriorWorker()',r'''void WarriorWorker(){while(g_running){if(!g_warriorEvent){Sleep(10);continue;}if(WaitForSingleObject(g_warriorEvent,50)!=WAIT_OBJECT_0)continue;HWND game=(HWND)g_warriorRequestWindow.load();for(;;){bool des=WarriorTakePending(g_warriorDescentPending),eq=false;if(!des)eq=WarriorTakePending(g_warriorEquipPending);if(!des&&!eq)break;WarriorSettings w;RogueSettings r;{std::lock_guard<std::mutex>lk(g_settingsMutex);w=g_warrior;r=g_rogue;}if(!w.enabled||!r.powerEnabled)continue;if(!game||GetForegroundWindow()!=game){g_warriorLastResult=3;continue;}if(des){bool ok=WarriorCastBarSlot(game,w.descentBar,w.descentSlot);g_warriorLastResult=ok?4:(GetForegroundWindow()==game?2:3);}else{int ph=g_warriorNextEquip.load()&1;bool ok=WarriorRightClickSlot(game,WarriorToggleSlot(w,ph));if(ok)g_warriorNextEquip=ph^1;g_warriorLastResult=ok?1:(GetForegroundWindow()==game?2:3);}PostMessageW(g_ui.main,WM_APP_REFRESH,0,0);}}}''')
_,e=span('void WarriorWorker()')
echo=r'''
void WarriorEchoWorker(){timeBeginPeriod(1);LARGE_INTEGER fq{};QueryPerformanceFrequency(&fq);LONGLONG next=0,step0=0;unsigned rev0=0;bool armed=false;while(g_running){WarriorSettings w;RogueSettings r;{std::lock_guard<std::mutex>lk(g_settingsMutex);w=g_warrior;r=g_rogue;}HWND game=(HWND)g_gameWindow.load();bool ready=w.enabled&&w.echoEnabled&&r.powerEnabled&&game&&IsWindow(game)&&GetForegroundWindow()==game&&!g_chatMode.load();unsigned rev=g_echoScheduleRevision.load();LONGLONG step=std::max<LONGLONG>(1,(LONGLONG)((long double)fq.QuadPart*(long double)WarriorEchoIntervalMs(w)/1000.0L));LARGE_INTEGER now{};QueryPerformanceCounter(&now);if(!ready){next=0;armed=false;rev0=rev;step0=step;Sleep(2);continue;}if(!armed||rev!=rev0||step!=step0){next=now.QuadPart;armed=true;rev0=rev;step0=step;}if(now.QuadPart<next){if((next-now.QuadPart)*1000>fq.QuadPart*2)Sleep(1);else SwitchToThread();continue;}bool ok=WarriorCastBarSlot(game,w.echoBar,w.echoSlot);LARGE_INTEGER after{};QueryPerformanceCounter(&after);if(ok){g_echoLastFireAt=GetTickCount64();g_echoFireCount.fetch_add(1);PostMessageW(g_ui.main,WM_APP_REFRESH,0,0);}next+=step;if(after.QuadPart-next>step)next=after.QuadPart+step;}timeEndPeriod(1);}
'''
s=s[:e]+echo+s[e:]

old='''g_ui.warriorSave=Ctrl(L"BUTTON",L"WARRIOR AYARLARINI KAYDET",BS_PUSHBUTTON,kContentX,392,238,28,IDC_WARRIOR_SAVE,g_fontBold);PageAdd(p,g_ui.warriorSave);PopulateWarriorUi();}'''
new='''PageAdd(p,Label(L"DESCENT",kContentX,386,68,20,g_fontBold));PageAdd(p,Label(L"Bar",kContentX+72,388,24,18,g_fontSmall));g_ui.warriorDescentBar=Ctrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL,kContentX+98,384,56,150,IDC_WARRIOR_DESCENT_BAR,g_fontSmall);FillBar(g_ui.warriorDescentBar);PageAdd(p,g_ui.warriorDescentBar);PageAdd(p,Label(L"Slot",kContentX+164,388,28,18,g_fontSmall));g_ui.warriorDescentSlot=Ctrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL,kContentX+194,384,54,150,IDC_WARRIOR_DESCENT_SLOT,g_fontSmall);FillSlot(g_ui.warriorDescentSlot);PageAdd(p,g_ui.warriorDescentSlot);g_ui.warriorDescentKey=Ctrl(L"BUTTON",L"Descent: F7",BS_PUSHBUTTON,kContentX+260,384,156,24,IDC_WARRIOR_DESCENT_KEY,g_fontSmall);PageAdd(p,g_ui.warriorDescentKey);\n  PageAdd(p,Label(L"ECHO",kContentX,420,50,20,g_fontBold));g_ui.warriorEchoEnable=Ctrl(L"BUTTON",L"Otomatik",BS_AUTOCHECKBOX,kContentX+54,418,70,22,IDC_WARRIOR_ECHO_ENABLE,g_fontSmall);PageAdd(p,g_ui.warriorEchoEnable);PageAdd(p,Label(L"Bar",kContentX+132,422,24,18,g_fontSmall));g_ui.warriorEchoBar=Ctrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL,kContentX+158,418,54,150,IDC_WARRIOR_ECHO_BAR,g_fontSmall);FillBar(g_ui.warriorEchoBar);PageAdd(p,g_ui.warriorEchoBar);PageAdd(p,Label(L"Slot",kContentX+220,422,28,18,g_fontSmall));g_ui.warriorEchoSlot=Ctrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL,kContentX+250,418,52,150,IDC_WARRIOR_ECHO_SLOT,g_fontSmall);FillSlot(g_ui.warriorEchoSlot);PageAdd(p,g_ui.warriorEchoSlot);PageAdd(p,Label(L"Süre",kContentX+310,422,30,18,g_fontSmall));g_ui.warriorEchoInterval=Ctrl(L"EDIT",L"30",WS_BORDER|ES_CENTER,kContentX+342,418,48,22,IDC_WARRIOR_ECHO_INTERVAL,g_fontSmall);PageAdd(p,g_ui.warriorEchoInterval);g_ui.warriorEchoUnit=Ctrl(L"COMBOBOX",L"",CBS_DROPDOWNLIST,kContentX+398,418,90,100,IDC_WARRIOR_ECHO_UNIT,g_fontSmall);SendMessageW(g_ui.warriorEchoUnit,CB_ADDSTRING,0,(LPARAM)L"Saniye");SendMessageW(g_ui.warriorEchoUnit,CB_ADDSTRING,0,(LPARAM)L"Dakika");PageAdd(p,g_ui.warriorEchoUnit);PageAdd(p,Label(L"Echo aktif olur olmaz bir kez basar; sonra sabit deadline ile sürer (kümülatif süre kayması yok).",kContentX,450,570,30,g_fontSmall));\n  g_ui.warriorSave=Ctrl(L"BUTTON",L"WARRIOR AYARLARINI KAYDET",BS_PUSHBUTTON,kContentX,488,238,28,IDC_WARRIOR_SAVE,g_fontBold);PageAdd(p,g_ui.warriorSave);PopulateWarriorUi();}'''
once(old,new,'warrior ui insert')

once('case WM_COMMAND:{int id=LOWORD(w);if((id==IDC_WARRIOR_SHIELD_SLOT||id==IDC_WARRIOR_WEAPON_SLOT)&&HIWORD(w)==EN_CHANGE){ReadWarriorUi(false);}','case WM_COMMAND:{int id=LOWORD(w);if((id==IDC_WARRIOR_SHIELD_SLOT||id==IDC_WARRIOR_WEAPON_SLOT||id==IDC_WARRIOR_ECHO_INTERVAL)&&HIWORD(w)==EN_CHANGE){ReadWarriorUi(false);}if(id==IDC_WARRIOR_DESCENT_BAR||id==IDC_WARRIOR_DESCENT_SLOT||id==IDC_WARRIOR_ECHO_ENABLE||id==IDC_WARRIOR_ECHO_BAR||id==IDC_WARRIOR_ECHO_SLOT||id==IDC_WARRIOR_ECHO_UNIT)ReadWarriorUi(false);','live ui')
once('case IDC_WARRIOR_SHIELD_KEY:g_assignTarget=8;SetWindowTextW(g_ui.warriorShieldKey,L"Bir tuşa bas...");break;case IDC_WARRIOR_CAL:','case IDC_WARRIOR_SHIELD_KEY:g_assignTarget=8;SetWindowTextW(g_ui.warriorShieldKey,L"Bir tuşa bas...");break;case IDC_WARRIOR_DESCENT_KEY:g_assignTarget=9;SetWindowTextW(g_ui.warriorDescentKey,L"Bir tuşa bas...");break;case IDC_WARRIOR_CAL:','cmd')
once('std::thread tMinor(MinorWorker),tR(RWorker),tCure(CureWorker),tAttack(AttackWorker),tWs(WsWorker),tVitals(VitalsWorker),tMobSkill(MobSkillWorker),tMobChase(MobChaseWorker),tMobScroll(MobScrollWorker),tMobPriest(MobPriestWorker),tWarrior(WarriorWorker);','std::thread tMinor(MinorWorker),tR(RWorker),tCure(CureWorker),tAttack(AttackWorker),tWs(WsWorker),tVitals(VitalsWorker),tMobSkill(MobSkillWorker),tMobChase(MobChaseWorker),tMobScroll(MobScrollWorker),tMobPriest(MobPriestWorker),tWarrior(WarriorWorker),tWarriorEcho(WarriorEchoWorker);','thread')
once('if(tWarrior.joinable())tWarrior.join();CloseBridge();','if(tWarrior.joinable())tWarrior.join();if(tWarriorEcho.joinable())tWarriorEcho.join();CloseBridge();','join')

fn('bool RunWarriorModelTest()',r'''bool RunWarriorModelTest(){int pass=0,total=0;std::ofstream f("warrior-model-test-report.txt",std::ios::trunc);auto t=[&](const char*n,bool ok){total++;if(ok)pass++;f<<n<<"="<<(ok?"PASS":"FAIL")<<"\n";};InventoryGrid g{};g.valid=true;g.left=100;g.top=200;g.cell=40;g.screenOrigin={10,20};POINT a=WarriorSlotCellCenter(g,1),s4=WarriorSlotCellCenter(g,4),b=WarriorSlotCellCenter(g,7),c=WarriorSlotCellCenter(g,8),d=WarriorSlotCellCenter(g,28);t("Slot1TopLeft",a.x==130&&a.y==240);t("Slot4FourthColumn",s4.x==250&&s4.y==240);t("Slot7TopRight",b.x==370&&b.y==240);t("Slot8SecondRow",c.x==130&&c.y==280);t("Slot28BottomRight",d.x==370&&d.y==360);{int W=1000,H=600,cell=38,left=710,top=315;std::vector<uint32_t> px((size_t)W*H,0x00202020u);auto line=[&](int x0,int y0,int x1,int y1){for(int y=std::max(0,y0);y<std::min(H,y1);y++)for(int x=std::max(0,x0);x<std::min(W,x1);x++)px[(size_t)y*W+x]=0x00E0C080u;};for(int j=0;j<8;j++)line(left+j*cell-1,top,left+j*cell+2,top+4*cell+1);for(int i=0;i<5;i++)line(left,top+i*cell-1,left+7*cell+1,top+i*cell+2);InventoryGrid q{};bool ok=DetectInventoryGridPixels(px,W,H,q);t("Synthetic7x4Detected",ok);t("SyntheticGridGeometry",ok&&std::abs(q.cell-cell)<=2&&std::abs(q.left-left)<=4&&std::abs(q.top-top)<=4);if(ok){q.screenOrigin={0,0};t("GridEdgeValidation",WarriorGridEdgeScore(px,W,H,q)>8.0);}else t("GridEdgeValidation",false);}WarriorSettings w{};w.shieldSlot=4;w.weaponSlot=11;w.shieldHotkey='X';w.weaponHotkey='X';w.descentBar=6;w.descentSlot=3;w.descentHotkey=VK_F7;t("ToggleStartsAtShieldSlot4",WarriorToggleSlot(w,0)==4);t("ToggleThenWeaponSlot11",WarriorToggleSlot(w,1)==11);t("OneSharedHotkey",w.shieldHotkey==w.weaponHotkey);t("DescentSeparateHotkey",w.descentHotkey!=w.shieldHotkey);t("DescentBarSlotMapping",BarToVk(w.descentBar)==VK_F6&&SlotToVk(w.descentSlot)=='3');w.echoIntervalValue=1;w.echoIntervalUnit=0;t("EchoOneSecond",WarriorEchoIntervalMs(w)==1000ULL);w.echoIntervalValue=2;w.echoIntervalUnit=1;t("EchoTwoMinutes",WarriorEchoIntervalMs(w)==120000ULL);LONGLONG due=100000,step=25000,finished=107000,next=due+step;t("EchoAbsoluteDeadlineNoDrift",next==125000&&next!=finished+step);std::atomic<unsigned> qn{2};bool q1=WarriorTakePending(qn),q2=WarriorTakePending(qn),q3=WarriorTakePending(qn);t("ManualPendingNoDrop",q1&&q2&&!q3);t("RightClickDownFlag",MOUSEEVENTF_RIGHTDOWN==0x0008);t("RightClickUpFlag",MOUSEEVENTF_RIGHTUP==0x0010);f<<"TOTAL="<<total<<"\nPASSED="<<pass<<"\n";return total==19&&pass==19;}''')

for x in ['WarriorEchoWorker','DESCENT','EchoOneSecond','ManualPendingNoDrop','Premium Plus Combo | v4.8.21']:
 if x not in s: raise RuntimeError(x)
p.write_text(s,encoding='utf-8',newline='\n');print('WARRIOR_DESCENT_ECHO_PATCH=PASS')
